name: Auto label PR from template

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply label based on PR template checkbox
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";

            const versionLabels = ["patch", "minor", "major"];
            let labelToAdd = null;

            if (/\[\s*x\s*\]\s*major/i.test(body)) {
              labelToAdd = "major";
            } else if (/\[\s*x\s*\]\s*minor/i.test(body)) {
              labelToAdd = "minor";
            } else if (/\[\s*x\s*\]\s*patch/i.test(body)) {
              labelToAdd = "patch";
            }

            // Remove existing version labels
            for (const label of versionLabels) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: label
              }).catch(() => {});
            }

            // Add detected label
            if (labelToAdd) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [labelToAdd]
              });
            }
